/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Abu
 */
public class Diagnose extends javax.swing.JFrame {

    /**
     * Creates new form Diagnose
     */
    public Diagnose() {
        Connect();
        initComponents();
       
    }
    
      Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs;
 public Diagnose(String id)  {
    
     initComponents();
          if(!"null".equals(id))
          {
         try {
             txtpno1.setText(id);
             Connect();
             pst=con.prepareStatement("select * from patient where patientno=?");
             pst.setString(1,id);
             rs=pst.executeQuery();
             if(rs.next())
             {
                 String dob= rs.getString("dob");
                 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                 Date d = sdf.parse(dob);
                 Calendar c = Calendar.getInstance();
                 c.setTime(d);
                 int year = c.get(Calendar.YEAR);
                 int month = c.get(Calendar.MONTH) + 1;
                 int date = c.get(Calendar.DATE);
                 LocalDate l1 = LocalDate.of(year, month, date);
                 LocalDate now1 = LocalDate.now();
                 Period diff1 = Period.between(l1, now1);
                 int age= diff1.getYears();
                 String age2= Integer.toString(age);
                 txtage.setText(age2);
                 
             }
             else{
                 JOptionPane.showMessageDialog(null, "Please select a patient first!", "Warning", JOptionPane.WARNING_MESSAGE);
             }
         } catch (SQLException ex) {
             Logger.getLogger(Diagnose.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ParseException ex) {
             Logger.getLogger(Diagnose.class.getName()).log(Level.SEVERE, null, ex);
         }
          
          }
       
   
    }
    
public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/lung_cancer_detector","root","");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Diagnose.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        work = new javax.swing.JComboBox();
        pollution = new javax.swing.JComboBox();
        alcohol = new javax.swing.JComboBox();
        dust = new javax.swing.JComboBox();
        genetic = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        weight = new javax.swing.JComboBox();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        chest = new javax.swing.JComboBox();
        jLabel48 = new javax.swing.JLabel();
        psmoker = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        smoking = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        obesity = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        diet = new javax.swing.JComboBox();
        lungdisease = new javax.swing.JComboBox();
        jLabel53 = new javax.swing.JLabel();
        fatigue = new javax.swing.JComboBox();
        swallowing = new javax.swing.JComboBox();
        breath = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        blood = new javax.swing.JComboBox();
        wheezing = new javax.swing.JComboBox();
        cold = new javax.swing.JComboBox();
        nails = new javax.swing.JComboBox();
        snoring = new javax.swing.JComboBox();
        cough = new javax.swing.JComboBox();
        gend = new javax.swing.JComboBox();
        txtpno1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jPanel4.setBackground(new java.awt.Color(51, 0, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Diagnosis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Patient No:");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Age:");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Gender");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Air Pollution:");

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Work Hazard:");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Dust Allergy:");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Alcohol Use:");

        work.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        work.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        pollution.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        alcohol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        dust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        genetic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        genetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Genetic Risk:");

        weight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Weight Loss:");

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Chest Pain:");

        chest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Passive Smoker:");

        psmoker.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        psmoker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psmokerActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Smoking:");

        smoking.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Obesity:");

        obesity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Balanced diet:");

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Clubbing Finger Nails:");

        diet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        diet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });

        lungdisease.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        lungdisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Fatigue:");

        fatigue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        fatigue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox14ActionPerformed(evt);
            }
        });

        swallowing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        swallowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });

        breath.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        breath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox16ActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Breath Shortness:");

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Difficult Swallowing:");

        jLabel56.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Frequent Cold:");

        jLabel57.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Dry Cough");

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Chronic Lung Disease:");

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Snoring:");

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Coughing Blood:");

        jLabel64.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Wheezing:");

        blood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodjComboBox13ActionPerformed(evt);
            }
        });

        wheezing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        wheezing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheezingjComboBox13ActionPerformed(evt);
            }
        });

        cold.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldjComboBox13ActionPerformed(evt);
            }
        });

        nails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        nails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nailsjComboBox13ActionPerformed(evt);
            }
        });

        snoring.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        snoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snoringjComboBox13ActionPerformed(evt);
            }
        });

        cough.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cough.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coughjComboBox13ActionPerformed(evt);
            }
        });

        gend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "1", "2" }));
        gend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendjComboBox1ActionPerformed(evt);
            }
        });

        txtpno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpno1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.setIconTextGap(2);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(alcohol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel45)
                            .addComponent(jLabel42))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(work, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genetic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pollution, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dust, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtage)
                                    .addComponent(gend, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                                .addComponent(txtpno1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jButton5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chest, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lungdisease, 0, 211, Short.MAX_VALUE)
                                .addComponent(diet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(obesity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(smoking, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(psmoker, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(cold, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                        .addGap(13, 13, 13)
                                        .addComponent(cough, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(nails, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(wheezing, javax.swing.GroupLayout.Alignment.LEADING, 0, 196, Short.MAX_VALUE)
                                    .addComponent(blood, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(snoring, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(breath, 0, 208, Short.MAX_VALUE)
                            .addComponent(weight, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(swallowing, 0, 196, Short.MAX_VALUE)
                            .addComponent(fatigue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lungdisease, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtpno1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(diet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gend, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel50)
                            .addComponent(obesity))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pollution, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(smoking, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cold, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(cough, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(snoring, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psmoker, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wheezing, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dust, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(work, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)))
                            .addComponent(genetic, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(swallowing, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(blood, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 14, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breath, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fatigue, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Stage 1 Diagnosis ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/refresh.png"))); // NOI18N
        jButton1.setText("Reset");
        jButton1.setIconTextGap(2);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/next.png"))); // NOI18N
        next.setText("Next");
        next.setEnabled(false);
        next.setIconTextGap(2);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/exit.png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.setIconTextGap(2);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/save.png"))); // NOI18N
        jButton4.setText("Save");
        jButton4.setIconTextGap(2);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(326, 326, 326))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton4)
                .addGap(72, 72, 72)
                .addComponent(jButton1)
                .addGap(68, 68, 68)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox16ActionPerformed

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jComboBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox14ActionPerformed

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void psmokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psmokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psmokerActionPerformed

    private void bloodjComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodjComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodjComboBox13ActionPerformed

    private void wheezingjComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheezingjComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wheezingjComboBox13ActionPerformed

    private void coldjComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldjComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldjComboBox13ActionPerformed

    private void nailsjComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nailsjComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nailsjComboBox13ActionPerformed

    private void snoringjComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snoringjComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snoringjComboBox13ActionPerformed

    private void coughjComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coughjComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coughjComboBox13ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
       String id=txtpno1.getText();
        Datasets ds= new Datasets(id);
       ds.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_nextActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void gendjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendjComboBox1ActionPerformed

    private void txtpno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpno1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String pno= txtpno1.getText(); //1
        String age= txtage.getText();  //2
        String gender= gend.getSelectedItem().toString();//3
        String airP= pollution.getSelectedItem().toString();//4
        String alcoholU= alcohol.getSelectedItem().toString();//5
        String dustA= dust.getSelectedItem().toString();//6
        String workHazard= work.getSelectedItem().toString();//7
        String geneticR= genetic.getSelectedItem().toString();//8
        String chronicD= lungdisease.getSelectedItem().toString();//9
        String balanceD= diet.getSelectedItem().toString();//10
        String obese = obesity.getSelectedItem().toString();//11
        String smoke = smoking.getSelectedItem().toString();//12
        String psmoke= psmoker.getSelectedItem().toString();//13
        String chestP= chest.getSelectedItem().toString();//14
        String weightL= weight.getSelectedItem().toString();//15
        String breathS= breath.getSelectedItem().toString();//16
        String fCold= cold.getSelectedItem().toString();//17
        String cNails= nails.getSelectedItem().toString();//18
        String dCough = cough.getSelectedItem().toString();//19
        String snore= snoring.getSelectedItem().toString();//20
        String wheeze= wheezing.getSelectedItem().toString();//21
        String cBlood = blood.getSelectedItem().toString();//22
        String dSwallow= swallowing.getSelectedItem().toString();//23
        String fatig= fatigue.getSelectedItem().toString();//24
       
        if(pno.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter the patient's number.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(age.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter patient's age.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(gender.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select patient's gender", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(airP.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Air Pollution", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(alcoholU.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Alcohol use", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(dustA.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Dust Allergy", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(workHazard.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Work Hazard", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(geneticR.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Genetic Risk", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(chronicD.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Chronic Lung Disease", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(balanceD.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Balanced Diet", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(obese.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Obesity", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(smoke.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Smoking", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(psmoke.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Passive Smoking", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(chestP.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Chest Pain", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(weightL.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Weight Loss", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(breathS.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Breath Shortness", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(fCold.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Frequent Cold", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(cNails.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Clubbing FingerNails", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(dCough.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Dry Cough", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(snore.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Snoring", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(wheeze.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Wheezing", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(cBlood.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Coughing Blood", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(dSwallow.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Difficult Swallowing", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else if(fatig.equals("select"))
        {
            JOptionPane.showMessageDialog(null, "Please select score for Fatigue", "Warning", JOptionPane.WARNING_MESSAGE);
        }
           else
        {
            try {
              pst=con.prepareStatement("select * from patient where patientno=?");
              pst.setString(1, pno);
              rs=pst.executeQuery();
              if(rs.next()){
                    pst=con.prepareStatement("select * from diagnosis where patientno=?");
                pst.setString(1,pno);
                rs=pst.executeQuery();
                if(rs.next())
                {
                   
                    int confirm=JOptionPane.showConfirmDialog(null, "Sorry! It seems patient the patient has already been diagnosed.\n. Do you wish to update the diagnosis details?", "Confirm", JOptionPane.YES_NO_OPTION);
                    if(confirm==JOptionPane.YES_OPTION)
                    {
                        pst=con.prepareStatement("update diagnosis set gender=?,air_pollution=?,alcohol_use=?,dust_allergy=?,work_hazard=?,genetic_risk=?,"
                                + "chronic_lung_disease=?,balance_diet=?,obesity=?,smoking=?,passive_smoking=?,chest_pain=?,weight_loss=?,breath_shortness=?,frequent_cold=?,clubbing_finger_nails=?,dry_cough=?,snoring=?,wheezing=?,coughing_blood=?,difficult_swallowing=?,fatigue=? where patientno=?");
                        pst.setString(1, gender);
                        pst.setString(2, airP);
                        pst.setString(3, alcoholU);
                        pst.setString(4, dustA);
                        pst.setString(5, workHazard);
                        pst.setString(6, geneticR);
                        pst.setString(7, chronicD);
                        pst.setString(8, balanceD);
                        pst.setString(9, obese);
                        pst.setString(10, smoke);
                        pst.setString(11, psmoke);
                        pst.setString(12, chestP);
                        pst.setString(13, weightL);
                        pst.setString(14, breathS);
                        pst.setString(15, fCold);
                        pst.setString(16, cNails);
                        pst.setString(17, dCough);
                        pst.setString(18, snore);
                        pst.setString(19, wheeze);
                        pst.setString(20, cBlood);
                        pst.setString(21, dSwallow);
                        pst.setString(22, fatig);
                        pst.setString(23, pno);
                    
                        int status=pst.executeUpdate();
                        if(status>0)
                        {
                            JOptionPane.showMessageDialog(null, "Patient diagnosis successfully updated\n Click next to continue with diagnosis","Success",JOptionPane.INFORMATION_MESSAGE);
                         next.setEnabled(true);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Patient diagnosis could not be updated", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                else{
                  pst=con.prepareStatement("insert into diagnosis(gender,air_pollution,alcohol_use,dust_allergy,work_hazard,genetic_risk,"
                                + "chronic_lung_disease,balance_diet,obesity,smoking,passive_smoking,chest_pain,weight_loss,breath_shortness,"
                          + "frequent_cold,clubbing_finger_nails,dry_cough,snoring,wheezing,coughing_blood,difficult_swallowing,fatigue,patientno,age) "
                          + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                        pst.setString(1, gender);
                        pst.setString(2, airP);
                        pst.setString(3, alcoholU);
                        pst.setString(4, dustA);
                        pst.setString(5, workHazard);
                        pst.setString(6, geneticR);
                        pst.setString(7, chronicD);
                        pst.setString(8, balanceD);
                        pst.setString(9, obese);
                        pst.setString(10, smoke);
                        pst.setString(11, psmoke);
                        pst.setString(12, chestP);
                        pst.setString(13, weightL);
                        pst.setString(14, breathS);
                        pst.setString(15, fCold);
                        pst.setString(16, cNails);
                        pst.setString(17, dCough);
                        pst.setString(18, snore);
                        pst.setString(19, wheeze);
                        pst.setString(20, cBlood);
                        pst.setString(21, dSwallow);
                        pst.setString(22, fatig);
                        pst.setString(23, pno);
                        pst.setString(24, age);
                     
                        int status= pst.executeUpdate();
                        if(status>0)
                        {
                            JOptionPane.showMessageDialog(null, "Patient diagnosis added successfully.\n Click next to continue", "Success", JOptionPane.INFORMATION_MESSAGE);
                            next.setEnabled(true);
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Patient diagnosis could not be added", "Success", JOptionPane.ERROR_MESSAGE);
                        }    
                    }
              }
              else{
                  JOptionPane.showMessageDialog(null,"Patient of "+ pno+" does not exist","Error",JOptionPane.ERROR_MESSAGE);
              }
            } catch (SQLException ex) {
                Logger.getLogger(Diagnose.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String pno= txtpno1.getText();
       if(pno.isEmpty())
       {
           JOptionPane.showMessageDialog(null, "Please enter patient number", "Warning", JOptionPane.WARNING_MESSAGE);
       }
       else{
           try {
               Connect();
               Boolean checkUser= false;
               pst=con.prepareStatement("select * from patient where patientno=?");
               pst.setString(1,pno);
               rs=pst.executeQuery();
               if(rs.next())
               {
                   checkUser=true;
               }
               if(checkUser==false)
               {
                   JOptionPane.showMessageDialog(null, "Patient with ID " + pno + " not found!", "Error", JOptionPane.ERROR_MESSAGE);
               }
               else{
                   String dob= rs.getString("dob");
                 SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                 Date d = sdf.parse(dob);
                 Calendar c = Calendar.getInstance();
                 c.setTime(d);
                 int year = c.get(Calendar.YEAR);
                 int month = c.get(Calendar.MONTH) + 1;
                 int date = c.get(Calendar.DATE);
                 LocalDate l1 = LocalDate.of(year, month, date);
                 LocalDate now1 = LocalDate.now();
                 Period diff1 = Period.between(l1, now1);
                 int age= diff1.getYears();
                 String age2= Integer.toString(age);
                 txtage.setText(age2);
               }
           } catch (SQLException ex) {
               Logger.getLogger(Diagnose.class.getName()).log(Level.SEVERE, null, ex);
           } catch (ParseException ex) {
               Logger.getLogger(Diagnose.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        txtpno1.setText("");
        txtage.setText(null);
        gend.setSelectedItem("select");
        pollution.setSelectedItem("select");
        alcohol.setSelectedItem("select");
        dust.setSelectedItem("select");
        work.setSelectedItem("select");
        genetic.setSelectedItem("select");
        lungdisease.setSelectedItem("select");
        diet.setSelectedItem("select");
        obesity.setSelectedItem("select");
        smoking.setSelectedItem("select");
        psmoker.setSelectedItem("select");
        chest.setSelectedItem("select");
        weight.setSelectedItem("select");
        breath.setSelectedItem("select");
        cold.setSelectedItem("select");
        nails.setSelectedItem("select");
        cough.setSelectedItem("select");
        snoring.setSelectedItem("select");
        wheezing.setSelectedItem("select");
        blood.setSelectedItem("select");
        swallowing.setSelectedItem("select");
        fatigue.setSelectedItem("select");
        
        JOptionPane.showMessageDialog(null,"Fields reset successfully","Success",JOptionPane.INFORMATION_MESSAGE);
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int confirm= JOptionPane.showConfirmDialog(null, "Are you sure to exit?", "Confirm", JOptionPane.YES_NO_OPTION);
       if(confirm==JOptionPane.YES_OPTION){
          Main m= new Main();
          m.setVisible(true);
           this.dispose();
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox alcohol;
    private javax.swing.JComboBox blood;
    private javax.swing.JComboBox breath;
    private javax.swing.JComboBox chest;
    private javax.swing.JComboBox cold;
    private javax.swing.JComboBox cough;
    private javax.swing.JComboBox diet;
    private javax.swing.JComboBox dust;
    private javax.swing.JComboBox fatigue;
    private javax.swing.JComboBox gend;
    private javax.swing.JComboBox genetic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox lungdisease;
    private javax.swing.JComboBox nails;
    private javax.swing.JButton next;
    private javax.swing.JComboBox obesity;
    private javax.swing.JComboBox pollution;
    private javax.swing.JComboBox psmoker;
    private javax.swing.JComboBox smoking;
    private javax.swing.JComboBox snoring;
    private javax.swing.JComboBox swallowing;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtpno1;
    private javax.swing.JComboBox weight;
    private javax.swing.JComboBox wheezing;
    private javax.swing.JComboBox work;
    // End of variables declaration//GEN-END:variables
}
